project_root: '%DOC_GEN_LIB_PATH%'
cache_dir: '%WORKING_DIR%/demo/demo3-add-missing-doc-blocks/__cache'
templates_dir: '%WORKING_DIR%/demo/demo3-add-missing-doc-blocks/templates'
language_handlers:
  php:
    class: \BumbleDocGen\LanguageHandler\Php\PhpHandler
    settings:
      async_source_loading_enabled: true
source_locators:
  - class: \BumbleDocGen\Core\Parser\SourceLocator\RecursiveDirectoriesSourceLocator
    arguments:
      directories:
        - "%project_root%/src"
